---
- name: Create validation server instances for MS target
  hosts: ms
  gather_facts: no
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ ms_ext_mgmt_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ ms_jmx_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ ui_http_port }}' }
  tags:
  - ds_read_ms
  - rmp_read_ms
  - qpid_read_ms
  - pg_read_ms

- name: Read check from validation server instances from DS
  hosts: ds
  gather_facts: no
  pre_tasks:
    - name: Construct group_id for target server
      set_fact:
        cacheable: yes
        group_id: "{{ target_region }}-ms"
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_ext_mgmt_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_jmx_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ui_http_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  tags:
  - ds_read_ms

- name: Read check from validation server instances from RMP
  hosts: rmp
  gather_facts: no
  pre_tasks:
  - name: Construct group_id for target server
    set_fact:
      cacheable: yes
      group_id: "{{ target_region }}-ms"
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_ext_mgmt_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_jmx_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ui_http_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  tags:
  - rmp_read_ms

- name: Read check from validation server instances from QPID
  hosts: qpid
  gather_facts: no
  pre_tasks:
  - name: Construct group_id for target server
    set_fact:
      cacheable: yes
      group_id: "{{ target_region }}-ms"
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_ext_mgmt_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_jmx_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ui_http_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  tags:
  - qpid_read_ms

- name: Read check from validation server instances from PG
  hosts: pg
  gather_facts: no
  pre_tasks:
  - name: Construct group_id for target server
    set_fact:
      cacheable: yes
      group_id: "{{ target_region }}-ms"
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_ext_mgmt_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ms_jmx_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ui_http_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  tags:
  - pg_read_ms

- name: Shutdown and clean up validation server instances from MS
  hosts: dc-2-ms
  gather_facts: no
  pre_tasks:
    - name: Construct group_id for target server
      set_fact:
        cacheable: yes
        group_id: "{{ target_region }}-ms"
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client-done, check_port: '{{ ms_ext_mgmt_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client-done, check_port: '{{ ms_jmx_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client-done, check_port: '{{ ui_http_port }}', target_server: "{{ hostvars[groups[group_id][0]].private_address }}" }
  tags:
  - read_ms_done
  - ds_read_ms
  - rmp_read_ms
  - qpid_read_ms
  - pg_read_ms







- hosts: ds
  gather_facts: no
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ cassandra_jmx_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ cassandra_thrift_client_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ cassandra_cql_native_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ cassandra_non_ssl_gossip_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ zk_data_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ zk_leader_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ zk_voter_port }}' }
  tags:
  - qs_read_ds

- hosts: qpid
  gather_facts: no
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_jmx_port }}', target_server: "{{ hostvars[groups['ds'][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_thrift_client_port }}', target_server: "{{ hostvars[groups['ds'][0]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_cql_native_port }}', target_server: "{{ hostvars[groups['ds'][0]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_non_ssl_gossip_port }}', target_server: "{{ hostvars[groups['ds'][0]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_data_port }}', target_server: "{{ hostvars[groups['ds'][0]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_leader_port }}', target_server: "{{ hostvars[groups['ds'][0]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_voter_port }}', target_server: "{{ hostvars[groups['ds'][0]].private_address }}"  }

  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_jmx_port }}', target_server: "{{ hostvars[groups['ds'][1]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_thrift_client_port }}', target_server: "{{ hostvars[groups['ds'][1]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_cql_native_port }}', target_server: "{{ hostvars[groups['ds'][1]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_non_ssl_gossip_port }}', target_server: "{{ hostvars[groups['ds'][1]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_data_port }}', target_server: "{{ hostvars[groups['ds'][1]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_leader_port }}', target_server: "{{ hostvars[groups['ds'][1]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_voter_port }}', target_server: "{{ hostvars[groups['ds'][1]].private_address }}"  }

  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_jmx_port }}', target_server: "{{ hostvars[groups['ds'][2]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_thrift_client_port }}', target_server: "{{ hostvars[groups['ds'][2]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_cql_native_port }}', target_server: "{{ hostvars[groups['ds'][2]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ cassandra_non_ssl_gossip_port }}', target_server: "{{ hostvars[groups['ds'][2]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_data_port }}', target_server: "{{ hostvars[groups['ds'][2]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_leader_port }}', target_server: "{{ hostvars[groups['ds'][2]].private_address }}"  }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ zk_voter_port }}', target_server: "{{ hostvars[groups['ds'][2]].private_address }}"  }
  tags:
  - qs_read_ds

- hosts: ldap
  gather_facts: no
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ ldap_data_port }}' }
  tags:
  - ms_read_ldap

- hosts: ms
  gather_facts: no
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ ldap_data_port }}', target_server: "{{ hostvars[groups['ldap'][0]].private_address }}" }
  tags:
  - ms_read_ldap

- name: Configure port connectivity validation server on Postgres ports
  hosts: pg
  gather_facts: no
  tags: ['pg']
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ pg_jmx_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ pg_int_mgmt_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ pg_db_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ pg_ext_mgmt_port }}' }

- name: Validate port connectivity with port connectivity client on Postgres ports
  hosts: pg
  gather_facts: no
  tags: ['pg']
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_jmx_port }}', target_server: "{{ hostvars[groups['pg'][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_int_mgmt_port }}', target_server: "{{ hostvars[groups['pg'][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_db_port }}', target_server: "{{ hostvars[groups['pg'][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_ext_mgmt_port }}', target_server: "{{ hostvars[groups['pg'][0]].private_address }}" }

  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_jmx_port }}', target_server: "{{ hostvars[groups['pg'][1]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_int_mgmt_port }}', target_server: "{{ hostvars[groups['pg'][1]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_db_port }}', target_server: "{{ hostvars[groups['pg'][1]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ pg_ext_mgmt_port }}', target_server: "{{ hostvars[groups['pg'][1]].private_address }}" }

- name: Configure port connectivity validation server on Postgres ports
  hosts: qpid
  gather_facts: no
  tags: ['qpid']
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ qpid_jmx_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ qpid_int_mgmt_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ qpid_messaging_port }}' }
  - { role: apigee-opdk-validate-external-port-connectivity-server, check_port: '{{ qpid_ext_mgmt_port }}' }


- hosts: pg
  gather_facts: no
  tags: ['qpid']
  roles:
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_jmx_port }}', target_server: "{{ hostvars[groups['qpid'][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_int_mgmt_port }}', target_server: "{{ hostvars[groups['qpid'][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_messaging_port }}', target_server: "{{ hostvars[groups['qpid'][0]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_ext_mgmt_port }}', target_server: "{{ hostvars[groups['qpid'][0]].private_address }}" }
    
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_jmx_port }}', target_server: "{{ hostvars[groups['qpid'][1]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_int_mgmt_port }}', target_server: "{{ hostvars[groups['qpid'][1]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_messaging_port }}', target_server: "{{ hostvars[groups['qpid'][1]].private_address }}" }
  - { role: apigee-opdk-validate-external-port-connectivity-client, check_port: '{{ qpid_ext_mgmt_port }}', target_server: "{{ hostvars[groups['qpid'][1]].private_address }}" }
