---
- hosts: planet
  vars_files:
  - /tmp/apigee-workspace/apigee/credentials.yml
  pre_tasks:
  - setup:
  - ec2_facts:
    when: "{{ ansible_bios_version | lower | search('amazon') }}"
  roles:
  - apigee-opdk-setup-default-settings

